services:
  app:
    build:
      context: .
      args:
        - DEV=true
    image: fit-charge:v1
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env

    depends_on:
      - db

  db:
    image: postgres:17-alpine3.21
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
     - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env

    depends_on:
      - db


volumes:
  dev-db-data:
  dev-static-data: