services:
  app:
    build:
      context: .
      args:
        - DEV=true
    image: fit-charge:v1
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
volumes:
  dev-static-data: