services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql://devuser:dev@123@db/devdb
      - DEBUG=1

    depends_on:
      - db

  db:
    image: postgres:17-alpine3.21
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=devdb
     - POSTGRES_USER=devuser
     - POSTGRES_PASSWORD=dev@123


volumes:
  dev-db-data:
  dev-static-data: