"""user log table added

Revision ID: 20a6a8cc9b52
Revises: 267daaf8c903
Create Date: 2025-12-03 21:06:52.146508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20a6a8cc9b52'
down_revision: Union[str, None] = '267daaf8c903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chest_cm')
    op.drop_column('user', 'biceps_cm')
    op.drop_column('user', 'hip_cm')
    op.drop_column('user', 'age')
    op.drop_column('user', 'height_cm')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'neck_cm')
    op.drop_column('user', 'weight_kg')
    op.drop_column('user', 'waist_cm')
    op.create_foreign_key(None, 'user_log', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_log', type_='foreignkey')
    op.add_column('user', sa.Column('waist_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('neck_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('hip_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('biceps_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('chest_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
