"""auto commit

Revision ID: 233de56e819b
Revises: 616fa6c8d3a8
Create Date: 2025-12-07 11:49:34.692857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '233de56e819b'
down_revision: Union[str, None] = '616fa6c8d3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
