"""country code added

Revision ID: 267daaf8c903
Revises: 68babdc85e0f
Create Date: 2025-12-02 07:45:38.210349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '267daaf8c903'
down_revision: Union[str, None] = '68babdc85e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('region', sa.String(), nullable=True))
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'region')
    # ### end Alembic commands ###
